# Generated by Django 5.1.2 on 2025-04-17 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_dislike'),
        ('users', '0003_perfilusuario_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricasSentimiento',
            fields=[
                ('publicacion', models.OneToOneField(db_column='publicacion_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='posts.publicacion')),
                ('sentimiento_promedio', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('subjetividad_promedio', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('total_comentarios', models.IntegerField(default=0)),
                ('comentarios_positivos', models.IntegerField(default=0)),
                ('comentarios_negativos', models.IntegerField(default=0)),
                ('comentarios_neutros', models.IntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(null=True)),
                ('comentarios_positivos_chatgpt', models.IntegerField(default=0)),
                ('comentarios_neutros_chatgpt', models.IntegerField(default=0)),
                ('comentarios_negativos_chatgpt', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'metricas_sentimiento',
            },
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='alquiler',
            name='instrucciones_devolucion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='terminos_aceptados',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='tracking_devolucion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='tracking_envio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='analizado_por_chatgpt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comentario',
            name='clasificacion_chatgpt',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='fecha_analisis',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='polaridad',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='subjetividad',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(null=True, upload_to='publicaciones/'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='comprador',
            field=models.ForeignKey(db_column='comprador_id', on_delete=django.db.models.deletion.CASCADE, related_name='ventas_compradas', to='users.usuario'),
        ),
    ]
